# Generated by Django 3.2.9 on 2021-11-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piec_CO', '0002_alter_temperature_in_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature_in',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
