# Generated by Django 3.2.9 on 2021-11-04 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piec_CO', '0003_alter_temperature_in_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temperature_in',
            new_name='TemperatureIn',
        ),
    ]
