# Generated by Django 3.2.9 on 2021-11-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piec_CO', '0004_rename_temperature_in_temperaturein'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('current_temperature', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('current_temperature', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
