# Generated by Django 3.2.9 on 2021-11-13 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piec_CO', '0005_temperatureout_temperaturereturn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperaturein',
            old_name='date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='temperatureout',
            old_name='date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='temperaturereturn',
            old_name='date',
            new_name='pub_date',
        ),
    ]
